version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      posthog:
        patterns:
          - "posthog-js"
          - "@posthog/*"
