# Deploy main app when anything outside /landing changes
# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Deploy Main App
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'landing/**'
      - '.github/**'
jobs:
  deploy:
    name: Deploy main app
    runs-on: ubuntu-latest
    concurrency: deploy-main-app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: npm
      - run: npm ci
      - run: npm run security:audit
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --yes
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
