# Deploy landing page when anything in /landing changes
# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Deploy Landing Page
on:
  push:
    branches:
      - main
    paths:
      - 'landing/**'
jobs:
  deploy:
    name: Deploy landing page
    runs-on: ubuntu-latest
    concurrency: deploy-landing
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config landing/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
